add nifti with freesurfer test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -67,6 +67,39 @@ jobs:
       #       fi
 
           
+  nifti_with_freesurfer:
+    <<: *dockersetup
+    steps:
+      - checkout
+      - run:
+          name: Check whether build should be skipped
+          command: |
+            cd /src/xcp_d
+            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?nifti_with_freesurfer\]' )" != "" ]]; then
+              echo "Skipping nifti_with_freesurfer build"
+              circleci step halt
+            fi
+      - run: *runinstall
+      - run:
+          name: Run full xcpd_d on nifti with freesurfer 
+          no_output_timeout: 1h
+          command: |
+            cd /src/xcp_d/.circleci
+            bash NiftiWithFreeSurferTest.sh
+
+  #     - run:
+  #         name: Checking outputs of nifti_with_freesurfer
+  #         command: |
+  #           qcfile=$(ls -f /tmp/nifti_with_freesurfer/xcp_d/sub-colornest001/ses-1/func/sub-colornest001_ses-1_task-rest_run-2_space-MNI152NLin2009cAsym_desc-qc_bold.csv)
+  #           if [[ -f ${qcfile} ]]; then 
+  #           echo "processing complete"
+  #              exit 0
+  #           else 
+  #           echo "there is error "
+  #               exit 1
+  #           fi
+
+
   # cifti_with_freesurfer:
   #   machine:
   #     image: ubuntu-2004:202010-01
@@ -116,52 +149,6 @@ jobs:
   #           fi
 
 
-  # nifti_with_freesurfer:
-  #   machine:
-  #     image: ubuntu-2004:202010-01
-  #   working_directory: /tmp/data
-  #   steps:
-  #     - checkout:
-  #         path: /home/circleci/src/xcp_d
-  #     - run:
-  #         name: Check whether build should be skipped
-  #         command: |
-  #           cd /home/circleci/src/xcp_d
-  #           if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?nifti_with_freesurfer\]' )" != "" ]]; then
-  #             echo "Skipping nifti_with_freesurfer build"
-  #             circleci step halt
-  #           fi
-  #     - run:
-  #         name: Setting up test
-  #         command: |
-  #           mkdir -p /tmp/nifti_with_freesurfer 
-  #     - run:
-  #         name: Run full xcpd_abcd on nifti with freesurfer 
-  #         no_output_timeout: 5h
-  #         command: |
-        
-  #           docker run --rm -it \
-  #               -v /tmp/data:/data/ \
-  #               -v /tmp/wkdir:/wkdir \
-  #               -v /tmp:/scrth \
-  #               -v /tmp/nifti_with_freesurfer/:/out \
-  #               pennlinc/xcp_d:latest \
-  #               /data/fmriprepdata/withfreesurfer/fmriprep \
-  #               /out   \
-  #               --despike  --head_radius 40 \
-  #               -w /scrth/wkdir_niftiF --smoothing 6 
-
-  #     - run:
-  #         name: Checking outputs of nifti_with_freesurfer
-  #         command: |
-  #           qcfile=$(ls -f /tmp/nifti_with_freesurfer/xcp_d/sub-colornest001/ses-1/func/sub-colornest001_ses-1_task-rest_run-2_space-MNI152NLin2009cAsym_desc-qc_bold.csv)
-  #           if [[ -f ${qcfile} ]]; then 
-  #           echo "processing complete"
-  #              exit 0
-  #           else 
-  #           echo "there is error "
-  #               exit 1
-  #           fi
 
 
   # deploy_docker:
@@ -218,17 +205,16 @@ workflows:
       #       tags:
       #         only: /.*/
               
-      # - nifti_with_freesurfer:
-      #     requires:
-      #       - get_data
-      #       - build
-      #     filters:
-      #       branches:
-      #         ignore:
-      #           - /docs?\/.*/
-      #           - /tests?\/.*/
-      #       tags:
-      #         only: /.*/
+      - nifti_with_freesurfer:
+          requires:
+            - build
+          filters:
+            branches:
+              ignore:
+                - /docs?\/.*/
+                - /tests?\/.*/
+            tags:
+              only: /.*/
 
       - nifti_without_freesurfer:
           requires:
